experiment:
  name: deeplab_v3_plus
  run_identifier: mdaso2f1hc_v7
  dataset: /mnt/fast/data/kidney/zarr/scale_1
  output_dir: ~/experiments
  file_format: sampling
lightning:
  max_epochs: 40
  precision: 16
  gpus: [1]
  num_sanity_val_steps: 0
dataset:
  tile_shape: [1024, 1024]
  train:
    samples_per_item: 250
  valid:
    val_size: 300
training:
  loss_name: lovasz_symmetric
  batch_size: 40
  num_workers: 12
validation: {}
optimizer:
  name: madgrad
scheduler:
  name: one_cycle
  interval: step
  options:
    max_lr: 0.001
    pct_start: 0.1
    div_factor: 100
    final_div_factor: 1000
early_stopping:
  enabled: false
checkpoint:
  monitor: avg_val_sorensen_dice
  mode: max
model: {encoder_name: "efficientnet-b4", encoder_weights: "imagenet"}
deformation:
  flip: false
  zoom_sigma: 0.18
transformers:
  image_size: 256
  resize: true
  normalize_only: false
  bcg: null
  blur: { prob: 0.3 }
  noise: { prob: 0.2 }
  flip: { prob: 0.5 }
  elastic: null
  ssr: null
  color: { prob: 0.3 }
use_wandb_logging: true
metrics:
  - {name: "sorensen_dice"}
  - {name: "recall"}
  - {name: "precision"}
  - {name: "balanced_accuracy"}
  - {name: "f1_score"}
