experiment:
  name: unet
  run_identifier: test
  dataset: /mnt/fast/data/kidney/zarr/scale_1
  output_dir: ~/experiments
  file_format: sampling
lightning:
  max_epochs: 30
  precision: 16
  gpus: [1]
  num_sanity_val_steps: 0
dataset:
  tile_shape: [1024, 1024]
  train:
    samples_per_item: 200
  valid:
    val_size: 300
training:
  loss_name: lovasz_symmetric
  batch_size: 40
  num_workers: 12
validation: {}
optimizer:
  name: madgrad
scheduler:
  name: one_cycle
  interval: step
  options:
    max_lr: 0.001
    pct_start: 0.12
    final_div_factor: 1000
early_stopping:
  enabled: false
checkpoint:
  monitor: avg_val_sorensen_dice
  mode: max
model: {encoder_name: "efficientnet-b4", encoder_weights: "imagenet"}
transformers:
  image_size: 256
  resize: true
  normalize_only: true
use_wandb_logging: true
metrics:
  - {name: "sorensen_dice"}
  - {name: "recall"}
  - {name: "precision"}
  - {name: "balanced_accuracy"}
  - {name: "f1_score"}
