# Single-fold training.
experiment:
  name: "unet"
  dataset: "/mnt/fast/data/kidney/alt_r4_s256_sat40_pix200_shift"
  output_dir: "~/experiments"
lightning:
  max_epochs: 100
  precision: 32
  gpus: [1]
  num_sanity_val_steps: 0
training:
  loss_name: "bce_jaccard"
  batch_size: 20
  num_workers: 12
validation: {}
optimizer:
  name: "adam"
  options: {lr: .005}
scheduler:
  name: "reduce_lr"
  monitor: "avg_val_dice"
  options:
    mode: "max"
    patience: 5
    factor: 0.3333
early_stopping:
  monitor: "avg_val_dice"
  mode: "max"
  patience: 10
  restore_best_weights: false
checkpoint:
  monitor: "avg_val_dice"
  mode: "max"
model: {encoder_name: "efficientnet-b4"}
transformers: {image_size: 256}
use_wandb_logging: true
metrics:
  - {name: "dice", sigmoid: True}
  - {name: "recall"}
  - {name: "precision"}
  - {name: "balanced_accuracy"}
  - {name: "f1_score"}