experiment:
  name: "unet"
  run_identifier: "zRp6P5NPZP_folds"
  dataset: "/mnt/fast/data/kidney/zarr/scale_2"
  output_dir: "~/experiments"
  file_format: "sampling"
lightning:
  max_epochs: 30
  precision: 16
  gpus: [0]
  num_sanity_val_steps: 0
dataset:
  tile_shape: [512, 512]
  train:
    samples_per_item: 100
  valid:
    val_size: 300
training:
  loss_name: "bce_logits"
  batch_size: 7
  num_workers: 12
validation: {}
optimizer:
  name: "madgrad"
scheduler:
  name: "one_cycle"
  interval: "step"
  options:
    max_lr: 0.001
    pct_start: 0.12
    final_div_factor: 1000
early_stopping:
  enabled: false
checkpoint:
  monitor: "avg_val_sorensen_dice"
  mode: "max"
model: {encoder_name: "efficientnet-b4", encoder_weights: "imagenet"}
transformers:
  image_size: 512
  resize: false
  normalize_only: true
use_wandb_logging: true
metrics:
  - {name: "sorensen_dice"}
  - {name: "recall"}
  - {name: "precision"}
  - {name: "balanced_accuracy"}
  - {name: "f1_score"}
